In [1]:
#2.1
import cv2
import numpy as np

img = np.zeros((8,8),dtype = np.uint8)
print('img=\n',img)

cv2.imshow('one',img)
print("读取像素点img[0,3]=",img[0,3])
img[0,3] = 255

print("修改后img=\n",img)
print("读取修改后像素点img[0,3]=",img[0,3])
cv2.imshow('two',img)

cv2.waitKey(0)
cv2.destroyAllWindows()

img=
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
读取像素点img[0,3]= 0
修改后img=
 [[  0   0   0 255   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]]
读取修改后像素点img[0,3]= 255


In [3]:
#2.2 
import cv2
img = cv2.imread('lena.jpg',0)
cv2.imshow('before',img)

for i in range(0,100):
    for j in range(80,100):
        img[i,j]=255
cv2.imshow('after',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
#2.3
import cv2 
import numpy as np

#----------------蓝色通道值------------------
blue = np.zeros((300,300,3), dtype=np.uint8)

blue[:,:,0] = 255
print("blue=\n",blue)
cv2.imshow("blue",blue)

#---------------绿色通道值---------------------
green = np.zeros((300,300,3), dtype=np.uint8)
green[:,:,1] = 255
print('green=\n',green)
cv2.imshow('green',green)

#--------------红色通道值---------------------
red = np.zeros((300,300,3),dtype = np.uint8)
red[:,:,2] = 255
print("red=\n",red)
cv2.imshow("red",red)

#-------------释放窗口-----------------------
cv2.waitKey(0)
cv2.destroyAllWindows()


blue=
 [[[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 ...

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]]
green=
 [[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255   0]
  [  

In [6]:
#2.4
import cv2
import numpy as np

img = np.zeros((300,300,3),dtype = np.uint8)
img[:,0:100,0]=255
img[:,100:200,1]=255
img[:,200:300,2]=255

cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyWindow('img')

In [7]:
#2.5
import numpy as np
img = np.zeros((2,4,3),dtype = np.uint8)
print('img=\n',img)
print("读取像素点img[0,3]=",img[0,3])
print("读取像素点img[1,2,2]=",img[1,2,2])

img[0,3] = 255
img[0,0] = [66,77,88]
img[1,1,1]=3
img[1,2,2]=4
img[0,2,0]=5

print("修改后img\n",img)
print("读取修改后像素点 img[1,2,2]=",img[1,2,2])

img=
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
读取像素点img[0,3]= [0 0 0]
读取像素点img[1,2,2]= 0
修改后img
 [[[ 66  77  88]
  [  0   0   0]
  [  5   0   0]
  [255 255 255]]

 [[  0   0   0]
  [  0   3   0]
  [  0   0   4]
  [  0   0   0]]]
读取修改后像素点 img[1,2,2]= 4


In [8]:
#2.6
import cv2
img =cv2.imread('lena.jpg')
cv2.imshow('before',img)
print('访问img[0,0]=',img[0,0])
print('访问img[0,0,0]=',img[0,0,0])
print('访问img[0,0,1]=',img[0,0,1])
print('访问img[0,0,2]=',img[0,0,2])
print('visit img[50,0]=',img[50,0])
print('visit img[100,0]=',img[100,0])

#region1
for i in range(0,50):
    for j in range(0,100):
        for k in range(0,3):
            img[i,j,k] = 255

#region2
for i in range(50,100):
    for j in range(0,100):
        for k in range(0,3):
            img[i,j,k] = 128
#region3
for i in range(100,150):
    for j in range(0,100):
        for k in range(0,3):
            img[i,j,k] = 0
cv2.imshow('after',img)

print('访问img[0,0]=',img[0,0])
print('访问img[0,0,0]=',img[0,0,0])
print('访问img[0,0,1]=',img[0,0,1])
print('访问img[0,0,2]=',img[0,0,2])
print('visit img[50,0]=',img[50,0])
print('visit img[100,0]=',img[100,0])

cv2.waitKey(0)
cv2.destroyAllWindows()

访问img[0,0]= [125 136 228]
访问img[0,0,0]= 125
访问img[0,0,1]= 136
访问img[0,0,2]= 228
visit img[50,0]= [ 68  56 156]
visit img[100,0]= [ 89  75 181]
访问img[0,0]= [255 255 255]
访问img[0,0,0]= 255
访问img[0,0,1]= 255
访问img[0,0,2]= 255
visit img[50,0]= [128 128 128]
visit img[100,0]= [0 0 0]


In [12]:
#2.7
import numpy as np
img = np.random.randint(10,99,size=[5,5],dtype = np.uint8)
print('img=\n',img)
print('readpixel img.item(3,2)=',img.item(3,2))
img.itemset((3,2),255)
print('img=\n',img)
print('readpixel img.item(3,2)=',img.item(3,2))

img=
 [[17 88 42 87 75]
 [30 69 50 12 93]
 [85 51 64 24 45]
 [28 97 76 52 97]
 [80 94 12 36 35]]
readpixel img.item(3,2)= 76
img=
 [[ 17  88  42  87  75]
 [ 30  69  50  12  93]
 [ 85  51  64  24  45]
 [ 28  97 255  52  97]
 [ 80  94  12  36  35]]
readpixel img.item(3,2)= 255


In [16]:
#2.8
import numpy as np
import cv2
img = np.random.randint(0,256,size=[256,256],dtype = np.uint8)
cv2.imshow('demo',img)
print('img=\n',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


img=
 [[164 176 116 ... 252   7 112]
 [ 23  97 234 ... 175 134  46]
 [ 37 246  90 ... 152 130  99]
 ...
 [237 182 248 ... 201 232 113]
 [ 51 243  82 ...  85 116  39]
 [ 51 113 176 ...  74 126  48]]


In [18]:
#2.9
import cv2
img = cv2.imread('lena.jpg',0)
print("read pixel img.item(3,2)=",img.item(3,2))
img.itemset((3,2),255)
print("read pixel img.item(3,2)=",img.item(3,2))
#test change region
cv2.imshow('before',img)
for i in range(10,100):
    for j in range(80,100):
        img.itemset((i,j),255)
cv2.imshow('after',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

read pixel img.item(3,2)= 159
read pixel img.item(3,2)= 255


In [19]:
#2.11
import cv2
import numpy as np
img = np.random.randint(0,255,size=[256,256,3],dtype = np.uint8)
cv2.imshow('demo',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
#2.13
import cv2
a = cv2.imread('lena.jpg')
face = a[100:200,100:180]
cv2.imshow('original',a)
cv2.imshow('face',face)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
#2.14
import cv2
import numpy as np
a = cv2.imread('lena.jpg')
cv2.imshow('original',a)
face = np.random.randint(0,256,size=[100,80,3],dtype = np.uint8)
a[100:200,100:180] = face
cv2.imshow('result',a)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [2]:
#2.16
import cv2
lena = cv2.imread('lena.jpg')
cv2.imshow('lena',lena)
b = lena[:,:,0]
g = lena[:,:,1]
r = lena[:,:,2]
cv2.imshow('b',b)
cv2.imshow('g',g)
cv2.imshow('r',r)
lena[:,:,0] = 0
cv2.imshow('b0',lena)
lena[:,:,1] = 0
cv2.imshow('b0g0',lena)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
#2.17
import cv2
lena = cv2.imread('lena.jpg')
b = cv2.split(lena)[0]
g = cv2.split(lena)[1]
r = cv2.split(lena)[2]
cv2.imshow('b',b)
cv2.imshow('g',g)
cv2.imshow('r',r)
b,g,r = cv2.split(lena)
cv2.imshow('B',b)
cv2.imshow('G',g)
cv2.imshow('R',r)

bgr = cv2.merge([b,g,r])
cv2.imshow('bgr',bgr)
rgb = cv2.merge([r,g,b])
cv2.imshow('rgb',rgb)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
#2.19
import cv2
gray = cv2.imread('lena.jpg',0)
color = cv2.imread('lena.jpg')

print('gray\n')
print('gray.shape=',gray.shape)
print('gray.size=',gray.size)
print('gray.dtype=',gray.dtype)

print('color\n')
print('color.shape=',color.shape)
print('color.size=',color.size)
print('color.dtype=',color.dtype)


gray

gray.shape= (256, 256)
gray.size= 65536
gray.dtype= uint8
color

color.shape= (256, 256, 3)
color.size= 196608
color.dtype= uint8


196608